pipeline {
    agent any

    stages {

        stage('Checkout Code From Git') {
            steps {
                git url: 'https://github.com/PavaretWisarut/ttb_test_pavaret.git', branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Test Automate') {
            steps {
                sh '''
                    python -m robot.run -L TRACE -d result -v LANG:th -v PLATFORM:api  -i feature:user_profile  testcases/
                '''
            }
        }

        stage('Send Result To Jenkins') {
            steps {
                archiveArtifacts artifacts: 'result/*', fingerprint: true
            }
        }
    }
}